name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      # Checkout the master branch
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Setup and download Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Build the page with Hugo after the changes
      - name: Build
        run: hugo --minify --verbose --gc

      # Upload artifacts (what the hell are those?)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:

      # Deploy takes the publish_dir and puts it in the new branch gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # Step lacking to use this as the branch to publish
